export enum OstfAppRecreationTypeEnum {
    PRIMARILY_PASSIVE_RECREATION = 'PRIMARILY_PASSIVE_RECREATION',
    PRIMARILY_ACTIVE_RECREATION = 'PRIMARILY_ACTIVE_RECREATION',
    BOTH = 'BOTH',
    NONE='NONE'
  }