export enum OstfAppAcquisitionTypeEnum {
    NONE = 'NONE',
    FEE_SIMPLE = 'FEE_SIMPLE',
    LESS_THAN_FEE_SIMPLE = 'LESS_THAN_FEE_SIMPLE',
    FEE_SIMPLE_AND_LESS_THAN_FEE_SIMPLE = 'FEE_SIMPLE_AND_LESS_THAN_FEE_SIMPLE'
  }